services:
  # MySQL база данных
  mysql:
    image: mysql:8.0
    container_name: tez_kyzmat_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: tez_kyzmat_root
      MYSQL_DATABASE: tez_kyzmat
      MYSQL_USER: tez_kyzmat_user
      MYSQL_PASSWORD: tez_kyzmat_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # phpMyAdmin для управления БД (опционально)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: tez_kyzmat_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: password
    ports:
      - "8080:80"
    depends_on:
      - mysql
    profiles:
      - admin

  # Redis для кэширования (опционально)
  redis:
    image: redis:7-alpine
    container_name: tez_kyzmat_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    profiles:
      - cache

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local

networks:
  default:
    name: tez_kyzmat_network
